[package]
name = "yonder-app"
description = "Yonder desktop app"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { workspace = true }
tokio = { workspace = true, features = ["net"] }
yonder-proto.workspace = true
yonder-client.workspace = true
